### ISSUE TITLE
Strange soundings when using german voices installed via pip 

### ISSUE THREAD

**Issue by joshjama** [MycroftAI/mimic3#14]
I installed idt as follows : 
$ pip install mycroft-mimic3-tts 
It works after then with : 
$ mimic3 -v="en_US" hello 
But if I try to use a german voice : 
$ mimic3 -v="de_DE" "Hallo" 
THe following output is given : 

Reading text from stdin...
INFO:mimic3_tts.tts:Loaded voice from /home/joshua/.local/share/mycroft/mimic3/voices/de_DE/thorsten_low
Traceback (most recent call last):
  File "/home/joshua/.local/bin/mimic3", line 8, in <module>
    sys.exit(main())
  File "/home/joshua/.local/lib/python3.8/site-packages/mimic3_tts/__main__.py", line 129, in main
    process_lines(state)
  File "/home/joshua/.local/lib/python3.8/site-packages/mimic3_tts/__main__.py", line 450, in process_lines
    process_line(line, state, line_id=line_id, line_voice=line_voice)
  File "/home/joshua/.local/lib/python3.8/site-packages/mimic3_tts/__main__.py", line 379, in process_line
    state.tts.speak_text(line)
  File "/home/joshua/.local/lib/python3.8/site-packages/mimic3_tts/tts.py", line 380, in speak_text
    for sent_phonemes, break_type in voice.text_to_phonemes(
  File "/home/joshua/.local/lib/python3.8/site-packages/mimic3_tts/voice.py", line 420, in text_to_phonemes
    for sentence in gruut.sentences(text, lang=text_language):
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/__init__.py", line 79, in sentences
    graph, root = text_processor(text, lang=lang, ssml=ssml, **process_args)
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/text_processor.py", line 441, in __call__
    return self.process(*args, **kwargs)
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/text_processor.py", line 690, in process
    self._pipeline_tokenize(
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/text_processor.py", line 1618, in _pipeline_tokenize
    in_lexicon = self._is_word_in_lexicon(word_text_norm, settings)
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/text_processor.py", line 2097, in _is_word_in_lexicon
    return bool(settings.lookup_phonemes(word, do_transforms=False))
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/lang.py", line 900, in __call__
    return self.phonemizer(word, role=role, do_transforms=do_transforms)
  File "/home/joshua/.local/lib/python3.8/site-packages/gruut/phonemize.py", line 91, in __call__
    cursor = self.db_conn.execute(
sqlite3.OperationalError: no such column: role
 screen joshua@joshua-HP-Spectre-x360-Convertible-13-ac0XX:     % CPU  12:50:11
 ~%

**Comment by synesthesiam** [comment]
Try `pip install mycroft-mimic3-tts[de]`
