### ISSUE TITLE
TypeError: Object of type set is not JSON serializable

### ISSUE THREAD

**Issue by greatAznur** [MycroftAI/mimic3#25]
hi
i  install in window and ubuntu and when i have specified a voice   i have the mesage ;

`ERROR:mimic3_http.app:Object of type set is not JSON serializable
Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\quart\app.py", line 1673, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "D:\Python\Python39\lib\site-packages\quart\app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "D:\Python\Python39\lib\site-packages\mycroft_mimic3_tts-0.2.3-py3.9.egg\mimic3_http\app.py", line 270, in api_voices
    return jsonify(voice_dicts)
  File "D:\Python\Python39\lib\site-packages\quart\json\__init__.py", line 32, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\quart\json\provider.py", line 205, in response
    return self._app.response_class(self.dumps(object_, **dump_args), mimetype=self.mimetype)
  File "D:\Python\Python39\lib\site-packages\quart\json\provider.py", line 171, in dumps
    return json.dumps(object_, **kwargs)
  File "D:\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Python\Python39\lib\site-packages\quart\json\provider.py", line 114, in _default
    raise TypeError(f"Object of type {type(object_).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable`

i have just a  fonctional with api and my web interface is not fonctional

**Comment by greatAznur** [comment]
my web interface is not fonctional : no selection for voice  all are empty
i have juste 1 voice fonctional with  a api

**Comment by greatAznur** [comment]
ok is my bad  all voice are fonctional  with api but  no with web interface

**Comment by synesthesiam** [comment]
Should be fixed in version 0.2.4
