### ISSUE TITLE
Mimic3 not working after reboot

### ISSUE THREAD

**Issue by TJH58** [MycroftAI/mimic3#39]
I installed and built Mimic3 source on a Manjaro Linux machine. After installed the source, everything worked fine. After reboot, I get the following error when trying to use a simple command:

[tim@tim-pc ~]$ mimic3 "Hello World!"
Reading text from stdin...
INFO:mimic3_tts.tts:Loaded voice from /usr/share/mycroft/mimic3/voices/en_UK/apope_low
ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so: cannot open shared object file: No such file or directory)
aplay: main:831: audio open error: No such device or address
Traceback (most recent call last):
  File "mimic3.py", line 40, in <module>
  File "mimic3_tts/__main__.py", line 129, in main
  File "mimic3_tts/__main__.py", line 481, in process_lines
  File "mimic3_tts/__main__.py", line 512, in play_wav_bytes
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['aplay', '-q', '/tmp/tmpl417ya40.wav']' returned non-zero exit status 1.
[1624] Failed to execute script 'mimic3' due to unhandled exception!

I then created the folder and copied the file here: /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so, but it just tells me another module that's missing.

**Comment by synesthesiam** [comment]
Sounds like a program you added or removed ended up installing/removing ALSA or PulseAudio.

**Comment by TJH58** [comment]
Michael,

Thank you for your reply. I did not install or uninstall any program. I only ran install on mimic3, and it worked after the install. I then restarted the computer, and it no longer works. I think it must be something with a path statement because it is not finding the lib file. I will look into this unless someone has another idea?

 
Regards and thank you for responding,

Tim

----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 03/30/23 15:18
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

Sounds like a program you added or removed ended up installing/removing ALSA or PulseAudio.

**Comment by synesthesiam** [comment]
You might want to reinstall `libasound2-plugins`

**Comment by TJH58** [comment]
Michael,

When I logged on this morning, Majaro indicated that there were updates. The list included all of the alsa audio stuff, including the plugins. So I ran all of the updates. I still get the same problems:

***@***.*** d11e]$ mimic3 "hello world"
Reading text from stdin...
INFO:mimic3_tts.tts:Loaded voice from /usr/share/mycroft/mimic3/voices/en_UK/apope_low
ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so: cannot open shared object file: No such file or directory)
aplay: main:831: audio open error: No such device or address
Traceback (most recent call last):
  File "mimic3.py", line 40, in <module>
  File "mimic3_tts/__main__.py", line 129, in main
  File "mimic3_tts/__main__.py", line 481, in process_lines
  File "mimic3_tts/__main__.py", line 512, in play_wav_bytes
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['aplay', '-q', '/tmp/tmpijww060x.wav']' returned non-zero exit status 1.
[4871] Failed to execute script 'mimic3' due to unhandled exception!
***@***.*** d11e]$

mimic3 works fine if I redirect the output to a .wav file. I can then run the .wav file with another app. But, this is irritating.
What is interesting is that mimic3 is looking for the lib in the directory x86_64-linux-gnu/alsa-lib/. This was used with wine, which I uninstalled before installing mimic3. Since then, I installed mimic3 a couple of different times, in different directories, with no success. I'm thinking that the x86_64-linux-gnu folder must be in a config file somewhere, but I'm not finding it.

Thank you for the idea. I was hoping it would work.
Tim

----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 03/31/23 14:21
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

You might want to reinstall libasound2-plugins

**Comment by TJH58** [comment]
Michael,

I just realized that the alsa plugins includes libasound, but not libasound2. Humm. Does mimic3 need the libasound2-plugins, or will it also work with libasound? The warning was for libasound. I know that Manjaro is behind other linux OSs when it comes to updates. Why would it work before a reboot though? It makes no sense.

Also, I did a global search for the x86_64-linux-gnu, but found nothing.


Tim

 
----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 03/31/23 14:21
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

You might want to reinstall libasound2-plugins

**Comment by synesthesiam** [comment]
This isn't really a mimic3 issue, it's related to "aplay" which mimic3 will call if you don't add the command line argument to save the WAV file.

**Comment by TJH58** [comment]
Michael,

OK. Hmm.

I ran aplay (aplay -q intro001.wav) and it plays the wav file just fine by itself. I'm wondering if the wav file is getting created by mimic3. Does it need libasound to do that? I don't see any wave files in the tmp folder. Does mimic3 delete them after use? If I copy the intro001.wav file to the tmp folder and run aplay -q /tmp/intro001.wav, it plays the wav file just fine.


Thank you for the thoughts. How can I tell if the wav file is being created?

Tim

----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 04/02/23 17:36
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

This isn't really a mimic3 issue, it's related to "aplay" which mimic3 will call if you don't add the command line argument to save the WAV file.

**Comment by TJH58** [comment]
Michael,

I ran across some discussions on the x86_64-linux-gnu. It appears that the folder structure is different on the different OSs. Debian and Arch (Manjaro) use the folders structures differently. I'm not sure if this has anything to do with it, but it could be that mimic3 will just not work correctly on Manjaro. I will look into this more.

Thanks again,


Tim

 
----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 04/02/23 17:36
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

This isn't really a mimic3 issue, it's related to "aplay" which mimic3 will call if you don't add the command line argument to save the WAV file.

**Comment by TJH58** [comment]
Michael,

FYI:

OK, so I found that the x86_64-linux-gnu folder has to do with Multiarch:

I thought the folder was related to wine, but I reinstalled wine and it was not there. So I did some searching on the x86_64-linux-gnu folder. It has to do with Multiarch:

"Multiarch is the term being used to refer to the capability to a system to install and run applications of multiple different binary targets on the same system. For example running a i386-linux-gnu application on an amd64-linux-gnu system." (See here for more information: https://wiki.debian.org/Multiarch)
It seems that mimic3 is looking to that folder for the x86 64 bit libraries. Arch/Manjaro only have the lib64 folder. So they break mimic3. I don't know why it works after install, before any reboot. Perhaps Python loads the libraries during compiling, and mimic3 uses the loaded libraries. Once the machine is rebooted, then mimic3 tries to load the libraries from x86_64-linux-gnu and fails because that location does not exist.

Tim

----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 04/02/23 17:36
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

This isn't really a mimic3 issue, it's related to "aplay" which mimic3 will call if you don't add the command line argument to save the WAV file.

**Comment by TJH58** [comment]
Michael,

Yes, I can use aplay apart from mimic3:


***@***.*** ~]$ cd Documents
***@***.*** Documents]$ cd audiobooks
***@***.*** audiobooks]$ cd d11e
***@***.*** d11e]$ cd "00 Introduction"
***@***.*** 00 Introduction]$ ls
intro001.txt  intro003.txt  intro005.txt  intro007.txt  intro009.txt
intro001.wav  intro003.wav  intro005.wav  intro007.wav  intro009.wav
intro002.txt  intro004.txt  intro006.txt  intro008.txt  intro010.txt
intro002.wav  intro004.wav  intro006.wav  intro008.wav  intro010.wav
***@***.*** 00 Introduction]$ aplay intro001.wav
Playing WAVE 'intro001.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
***@***.*** 00 Introduction]$

The audio comes through just fine.


Tim

 
----- Original Message -----
From: Michael Hansen ***@***.***)
Date: 04/04/23 12:59
To: MycroftAI/mimic3 ***@***.***)
Cc: Tim ***@***.***), Author ***@***.***)
Subject: Re: [MycroftAI/mimic3] Mimic3 not working after reboot (Issue #39)

Are you able to use aplay apart from Mimic 3?

**Comment by taiyu-len** [comment]
Hello, Ive come across this issue too.

The cause is mimic3 introducing new environment variables, which causes the aplay to fail.

specifically, `LD_LIBRARY_PATH`

the solution should simply be to unset that from `os.environ` before the `subprocess.check_output` call.
if you dont wish to change environ for anything else, making a copy and passing a unset version via the `env=` parameter to check_output would work as well.
