### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Kzer-Za** [MycroftAI/mimic3#46]
The example with `mimic3 'Hello world.' | aplay` works just fine. However, when I start `mimic3-server`, I am greeted by some errors:

```
INFO:mimic3_http.__main__:Starting web server
ERROR:mimic3_http.app:Error setting up swagger UI page
Traceback (most recent call last):
  File "mimic3_http/app.py", line 338, in get_app
  File "swagger_ui/__init__.py", line 13, in api_doc
Exception: No match application isinstance type!
[2023-08-25 22:58:35 +0300] [70595] [INFO] Running on http://0.0.0.0:59125 (CTRL + C to quit)
INFO:hypercorn.error:Running on http://0.0.0.0:59125 (CTRL + C to quit)
```

Then, after opening the web-interface, if I select any language other than EN-UK, the web interface displays this error: `URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>`. Below I give the more detailed output from the console:

```
ERROR:mimic3_http.synthesis:Error during inference
Traceback (most recent call last):
  File "urllib/request.py", line 1346, in do_open
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "http/client.py", line 1424, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mimic3_http/synthesis.py", line 125, in do_synthesis_proc
  File "mimic3_http/synthesis.py", line 81, in do_synthesis
  File "mimic3_http/synthesis.py", line 61, in do_synthesis
  File "mimic3_tts/tts.py", line 368, in speak_text
  File "mimic3_tts/tts.py", line 569, in _get_or_load_voice
  File "mimic3_tts/tts.py", line 621, in _download_voice
  File "mimic3_tts/download.py", line 121, in download_voice
  File "urllib/request.py", line 214, in urlopen
  File "urllib/request.py", line 517, in open
  File "urllib/request.py", line 534, in _open
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 1389, in https_open
  File "urllib/request.py", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
ERROR:mimic3_http.app:<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
Traceback (most recent call last):
  File "urllib/request.py", line 1346, in do_open
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "http/client.py", line 1424, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quart/app.py", line 1673, in full_dispatch_request
  File "quart/app.py", line 1718, in dispatch_request
  File "mimic3_http/app.py", line 215, in app_tts
  File "mimic3_http/app.py", line 103, in text_to_wav
  File "mimic3_http/synthesis.py", line 125, in do_synthesis_proc
  File "mimic3_http/synthesis.py", line 81, in do_synthesis
  File "mimic3_http/synthesis.py", line 61, in do_synthesis
  File "mimic3_tts/tts.py", line 368, in speak_text
  File "mimic3_tts/tts.py", line 569, in _get_or_load_voice
  File "mimic3_tts/tts.py", line 621, in _download_voice
  File "mimic3_tts/download.py", line 121, in download_voice
  File "urllib/request.py", line 214, in urlopen
  File "urllib/request.py", line 517, in open
  File "urllib/request.py", line 534, in _open
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 1389, in https_open
  File "urllib/request.py", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
```

1. Start `mimic3-server` and open `http://localhost:59125`
2. Click on 'speak' without changing the default language or default text
3. See error `URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>`

**Expected behavior**
The text in the input field should be spoken in the selected (i.e. default) language.

**Environment (please complete the following information):**
 - Device type: desktop
 - OS: Manjaro Linux
 - Mycroft-core version: not installed
 - Other versions: Python 3.11.3-2

**Additional context**
No modifications to source code or config files.

If I change in the web-interface the language to `English (UK)`, it is spoken as it is supposed to be.

**Comment by termermc** [comment]
I'm having the same issue with and without the server. If it's anything besides `en_UK/apope_low`, it has this issue.

**Comment by lukemilby** [comment]
Im running this on a M1 Mac Book Pro. I fixed this by removing the cert sharing thats setup in the scripts.

**Delete that shit**
```bash
if [[ -d /etc/ssl/certs ]]; then
    # This directory seems to usually have symlinks to other directories
    docker_run_args+=('-v' '/etc/ssl/certs:/etc/ssl/certs:ro')

    # Create temp file with all certificate directories found
    cert_dirs_file="$(mktemp)"
    function finish {
        rm -rf "${cert_dirs_file}"
    }
    trap finish EXIT

    while read -r cert_path; do
        # Follow symlinks and record directory paths
        cert_path="$(readlink -f "${cert_path}")"
        cert_dir="$(dirname "${cert_path}")"
        echo $cert_dir >> "${cert_dirs_file}"
    done < <(find /etc/ssl/certs -name '*.pem' -type l)

    # Map unique certificate directories
    while read -r cert_dir; do
        docker_run_args+=('-v' "${cert_dir}:${cert_dir}:ro")
    done < <(sort < "${cert_dirs_file}" | uniq)
fi
```
