### ISSUE TITLE
Mimic does not work in in conda environment, venv, or just in general

### ISSUE THREAD

**Issue by PhilipAmadasun** [MycroftAI/mimic3#57]
I am trying to use mimc3 in python and I basically get the same results not matter what I try. I have the voices `en_UK/apope_low`  and `en_US/cmu-arctic_low` in my directory `~/.local/share/mycroft/mimic3/voices`. But mimic3 can't find them. So I leave `Mimic3TTSPlugin()` blank to get maybe some default voice but I get an error. For context I have tried installing mimic3 in different environments (conda, venv within conda, venv outside conda) and I've used python 3.9 and 3.12. Every thing gives the same results as below.
```
>>> from ovos_tts_plugin_mimic3 import Mimic3TTSPlugin
2024-05-21 20:02:34.068 - OVOS - ovos_utils.messagebus:<module>:9 - WARNING - Deprecation version=0.1.0. Caller=ovos_plugin_manager.templates.audio:9. decode_binary_message, send_binary_file_message, send_binary_data_message,     send_message, wait_for_reply, listen_once_for_message, get_message_lang, get_websocket, get_mycroft_bus,     listen_for_message have moved to ovos_bus_client.util
2024-05-21 20:02:34.094 - OVOS - ovos_utils.messagebus:<module>:12 - WARNING - Deprecation version=0.1.0. Caller=ovos_plugin_manager.templates.audio:9. dig_for_message, FakeMessage, FakeBus moved to ovos_utils.fakebus



>>> cfg = {"voice": "en_US/cmu-arctic_low"}


>>> mimic = Mimic3TTSPlugin(cfg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/ovos_tts_plugin_mimic3/__init__.py", line 43, in __init__
    if lang not in self.default_voices:
TypeError: unhashable type: 'dict'



>>> mimic = Mimic3TTSPlugin()
2024-05-21 20:05:41.560 - OVOS - ovos_plugin_manager.utils:load_plugin:155 - WARNING - Could not find the plugin ovos.plugin.g2p.ovos-g2p-plugin-heuristic-arpa
2024-05-21 20:05:41.561 - OVOS - ovos_plugin_manager.g2p:create:142 - ERROR - The selected G2P plugin could not be loaded.
Traceback (most recent call last):
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
TypeError: 'NoneType' object is not callable
2024-05-21 20:05:41.562 - OVOS - ovos_plugin_manager.templates.tts:__init__:205 - ERROR - G2P plugin not loaded, there will be no mouth movements
Traceback (most recent call last):
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/ovos_plugin_manager/templates/tts.py", line 203, in __init__
    self.g2p = OVOSG2PFactory.create(cfg)
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
TypeError: 'NoneType' object is not callable
2024-05-21 20:05:41.575 - OVOS - ovos_plugin_manager.templates.tts:add_metric:277 - ERROR - 'Mimic3TTSPlugin' object has no attribute 'log_timestamps'
Traceback (most recent call last):
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/ovos_plugin_manager/templates/tts.py", line 274, in add_metric
    if self.log_timestamps:
AttributeError: 'Mimic3TTSPlugin' object has no attribute 'log_timestamps'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/ovos_tts_plugin_mimic3/__init__.py", line 94, in __init__
    self.tts.preload_voice(voice)
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/mimic3_tts/tts.py", line 310, in preload_voice
    self._get_or_load_voice(key_to_load)
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/mimic3_tts/tts.py", line 595, in _get_or_load_voice
    voice = Mimic3Voice.load_from_directory(
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/mimic3_tts/voice.py", line 283, in load_from_directory
    onnx_model = Mimic3Voice._load_model(
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/mimic3_tts/voice.py", line 403, in _load_model
    onnx_model = onnxruntime.InferenceSession(
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/philip/miniconda3/envs/mimic3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 307, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/philip/.local/share/mycroft/mimic3/voices/en_US/cmu-arctic_low/generator.onnx failed:Protobuf parsing failed.
```

**Comment by synesthesiam** [comment]
This should be posted as an issue in the OVOS repo: https://github.com/OpenVoiceOS/ovos-tts-plugin-mimic3

**Comment by snwfdhmp** [comment]
Any update on this ? I'm blocked by this
